# Setup
title:               On Raz
description:         Raz's Blog
tagline:             Raz's Blog about life as a Software Engineer.
paginate:            5
url:                 https://onraz.github.io/

# About/contact
author:
  name:              Razib Shahriar
  url:               https://www.linkedin.com/in/onraz
  email:             razibh@gmail.com

# Gems
gems:                [jekyll-paginate]

# Custom vars
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - node_modules
