# Setup
title:               On Raz
description:         Raz's Blog
tagline:             Life as a Software Engineer.
paginate:            5

# About/contact
author:
  name:              Razib Shahriar
  url:               https://www.linkedin.com/in/onraz
  email:             razibh@gmail.com

# Gems
gems:                [jekyll-paginate]

# Custom vars
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - node_modules
  
  
  
# Prose

prose:
  rooturl: '_posts'
  siteurl: 'https://onraz.github.io'
  media: 'assets'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          alterable: true
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "language"
              value: "language"
            - name: "concurrency"
              value: "concurrency"
            - name: "distributed"
              value: "distributed"
            - name: "algorithm"
              value: "algorithm"
